---
title: "14_ngsDist_heatmap"
output: html_document
---

```{r setup, include=FALSE}
#Set fuctions to plot MDSs and heatmaps from different axis settings.

knitr::opts_chunk$set(echo = TRUE)

#packages
library(lattice) 
library(methods)
library(optparse)
library(ggplot2)
library(pheatmap)

#metadata is first made in a CSV file as "metadata_##worms.txt"; placed in the working folder.
#Worm_ID	Haplotype_group	Location Collection_year
#OalgA10CA	A	Cavoli	2016
#OalgA10SA	A	SantAndrea	2016
#OalgA4CA		A	Cavoli	2016

#Output files from step 12 (ANGSD - ngsDist; .dist and .mds) files need to be placed in the working folder.

dist_plot <- function(annot_file, mytitle, input_header) {
 pdf(paste("Heatmap ",mytitle,".pdf", sep=""),width=8,height=8)
  data1 <- read.table(file = paste(input_header,".dist", sep=""), sep="\t", header = F, skip = 2, row.names = 1)
  colnames(data1)<-rownames(data1)
  as.data.frame (data1, skip = 1, colnames =1)
  data1.mat<-as.matrix(data1)
  pheatmap(data1.mat, symm = T)
 dev.off()
 annot <- read.table(file=annot_file, sep="\t", header=T)
 mds <- read.table(file=paste(input_header,".mds", sep=""), stringsAsFact=F)
 title = paste("MDS ",mytitle)
 PC <- as.data.frame(mds)
 colnames(PC) <-paste(rep("PC",ncol(mds)), 1:ncol(mds), sep="")
 PC$Worm_ID <- factor(annot$Worm_ID)
 PC$Haplotype_group <- factor(annot$Haplotype_group)
 PC$Collection_year <- factor(annot$Collection_year)
 PC$Location <- factor(annot$Location, levels = c("Capo_Vita","Sorgente","Sant_Andrea","Zuccale","Seccheto","Cavoli","Cala_del_Fico","Pomonte","Son_Serra","Bella_Dona","Magaluf"))
 tmp <- unlist(strsplit(colnames(mds), split="_"))   #Extract variation
 val <- as.numeric(tmp[seq(2,length(tmp),2)])        #Variation
 rm(tmp)
 ggplot(PC,aes(x=PC1, y=PC2, colour=Location, label=Worm_ID))+
  geom_point(size=3, alpha=0.5)+
  geom_text(size=2.5)+
  ggtitle(title)+
  xlab(paste("Dimension1 (",signif(val[1], digits=3),"%)",sep="",collapse=""))+
  ylab(paste("Dimension2 (",signif(val[2], digits=3),"%)",sep="",collapse=""))+
  theme_classic() + theme(plot.title = element_text(size=12))+
  ggsave(paste(title,".pdf", sep=""), width = 8, height = 6.5)
 ggplot(PC,aes(x=PC1, y=PC2, colour=Location, label=Worm_ID))+
  geom_point(size=5, alpha=0.5)+
  ggtitle(title)+
  xlab(paste("Dimension1 (",signif(val[1], digits=3),"%)",sep="",collapse=""))+
  ylab(paste("Dimension2 (",signif(val[2], digits=3),"%)",sep="",collapse=""))+
  theme_classic() + theme(plot.title = element_text(size=12))+
  ggsave(paste(title,"_noLabel_loc.pdf", sep=""), width = 8, height = 6.5)
 ggplot(PC,aes(x=PC1, y=PC2, colour=Haplotype_group, label=Worm_ID))+
  geom_point(size=5, alpha=0.5)+
  ggtitle(title)+
  xlab(paste("Dimension1 (",signif(val[1], digits=3),"%)",sep="",collapse=""))+
  ylab(paste("Dimension2 (",signif(val[2], digits=3),"%)",sep="",collapse=""))+
  theme_classic() + theme(plot.title = element_text(size=12))+
  ggsave(paste(title,"_noLabel_haplo.pdf", sep=""), width = 8, height = 6.5)
 ggplot(PC,aes(x=PC1, y=PC2, colour=Location, shape=Haplotype_group, label=Worm_ID))+
  geom_point(size=5, alpha=0.5)+
  ggtitle(title)+
  xlab(paste("Dimension1 (",signif(val[1], digits=3),"%)",sep="",collapse=""))+
  ylab(paste("Dimension2 (",signif(val[2], digits=3),"%)",sep="",collapse=""))+
  theme_classic() + theme(plot.title = element_text(size=12))+
  scale_shape_manual(values = c(16,17,15,18,7,13,9,8,12,1,2,3,4,5,6,10)) +
  ggsave(paste(title,"_noLabel_loc_haplo.pdf", sep=""), width = 8, height = 6.5)
}

dist_plot_xr <- function(annot_file, mytitle, input_header) {
 pdf(paste("Heatmap ",mytitle,".pdf", sep=""),width=8,height=8)
  data1 <- read.table(file = paste(input_header,".dist", sep=""), sep="\t", header = F, skip = 2, row.names = 1)
  colnames(data1)<-rownames(data1)
  as.data.frame (data1, skip = 1, colnames =1)
  data1.mat<-as.matrix(data1)
  pheatmap(data1.mat, symm = T)
 dev.off()
 annot <- read.table(file=annot_file, sep="\t", header=T)
 mds <- read.table(file=paste(input_header,".mds", sep=""), stringsAsFact=F)
 title = paste("MDS ",mytitle)
 PC <- as.data.frame(mds)
 colnames(PC) <-paste(rep("PC",ncol(mds)), 1:ncol(mds), sep="")
 PC$Worm_ID <- factor(annot$Worm_ID)
 PC$Haplotype_group <- factor(annot$Haplotype_group)
 PC$Collection_year <- factor(annot$Collection_year)
 PC$Location <- factor(annot$Location, levels = c("Capo_Vita","Sorgente","Sant_Andrea","Zuccale","Seccheto","Cavoli","Cala_del_Fico","Pomonte","Son_Serra","Bella_Dona","Magaluf"))
 tmp <- unlist(strsplit(colnames(mds), split="_"))   #Extract variation
 val <- as.numeric(tmp[seq(2,length(tmp),2)])        #Variation
 rm(tmp)
 ggplot(PC,aes(x=PC1, y=PC2, colour=Location, label=Worm_ID))+
  geom_point(size=3, alpha=0.5)+
  geom_text(size=2.5)+
  ggtitle(title)+
  xlab(paste("Dimension1 (",signif(val[1], digits=3),"%)",sep="",collapse=""))+
  ylab(paste("Dimension2 (",signif(val[2], digits=3),"%)",sep="",collapse=""))+
  theme_classic() + theme(plot.title = element_text(size=12))+
  scale_x_reverse() +
  ggsave(paste(title,".pdf", sep=""), width = 8, height = 6.5)
 ggplot(PC,aes(x=PC1, y=PC2, colour=Location, label=Worm_ID))+
  geom_point(size=5, alpha=0.5)+
  ggtitle(title)+
  xlab(paste("Dimension1 (",signif(val[1], digits=3),"%)",sep="",collapse=""))+
  ylab(paste("Dimension2 (",signif(val[2], digits=3),"%)",sep="",collapse=""))+
  theme_classic() + theme(plot.title = element_text(size=12))+
  scale_x_reverse() +
  ggsave(paste(title,"_noLabel_loc.pdf", sep=""), width = 8, height = 6.5)
 ggplot(PC,aes(x=PC1, y=PC2, colour=Haplotype_group, label=Worm_ID))+
  geom_point(size=5, alpha=0.5)+
  ggtitle(title)+
  xlab(paste("Dimension1 (",signif(val[1], digits=3),"%)",sep="",collapse=""))+
  ylab(paste("Dimension2 (",signif(val[2], digits=3),"%)",sep="",collapse=""))+
  theme_classic() + theme(plot.title = element_text(size=12))+
  scale_x_reverse() + 
  ggsave(paste(title,"_noLabel_haplo.pdf", sep=""), width = 8, height = 6.5)
 ggplot(PC,aes(x=PC1, y=PC2, colour=Location, shape=Haplotype_group, label=Worm_ID))+
  geom_point(size=5, alpha=0.5)+
  ggtitle(title)+
  xlab(paste("Dimension1 (",signif(val[1], digits=3),"%)",sep="",collapse=""))+
  ylab(paste("Dimension2 (",signif(val[2], digits=3),"%)",sep="",collapse=""))+
  theme_classic() + theme(plot.title = element_text(size=12))+
  scale_shape_manual(values = c(16,17,15,18,7,13,9,8,12,1,2,3,4,5,6,10)) +
  scale_x_reverse() + 
  ggsave(paste(title,"_noLabel_loc_haplo.pdf", sep=""), width = 8, height = 6.5)
}
```



```{r}
#dist_plot <- function(annot_file, mytitle, input_header)
#dist_plot_xr <- function(annot_file, mytitle, input_header)  #X-axis reversed

#Oalg data set and new Oalg_verC3 reference + region-filter. (5-80%, MaxDepthInd4, GL2)
#Dist and MDS files were made from the previous ANGSD run
setwd("results/12_ngs_dist_region")
##
dist_plot_xr("metadata_180810_310_oalg.txt","310worms_OalgC3_prior1_minMAF0.01_ind0.5_5-80%dep_GL2_rf", "310Samples_to_Oalg_verC3_MinQ20_SNPpval1e-3_Prior1")

dist_plot("metadata_180810_286_oalg_elba.txt","286worms_OalgC3_prior1_minMAF0.01_ind0.5_5-80%dep_GL2_rf", "286Samples_to_Oalg_verC3_MinQ20_SNPpval1e-3_Prior1")
```